version: '3'

services:
  kill-the-newsletter:
    build:
      context: .
      args:
        VERSION: v1.0.1
    ports:
      - "127.0.0.1:8007:80"
      - "25:25"
    restart: always
    volumes:
      - data:/data
    environment:
      DATA_DIRECTORY: /data
      WEB_URL: ${WEB_URL}
      EMAIL_URL: ${EMAIL_URL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}

volumes:
  data:
