version: '3'
services:
  wallabag:
    image: wallabag/wallabag:2.5.4
    restart: always
    environment:
      SYMFONY__ENV__SECRET: ${SECRET}
      SYMFONY__ENV__DOMAIN_NAME: ${DOMAIN_NAME}
      SYMFONY__ENV__SENTRY_DSN: ${SENTRY_DSN}
      SYMFONY__ENV__SERVER_NAME: ${SERVER_NAME}
      SYMFONY__ENV__FROM_EMAIL: ${FROM_EMAIL}
      SYMFONY__ENV__MAILER_HOST: ${MAILER_HOST}
      SYMFONY__ENV__MAILER_PORT: ${MAILER_PORT}
      SYMFONY__ENV__MAILER_ENCRYPTION: ssl
      SYMFONY__ENV__MAILER_USER: ${MAILER_USER}
      SYMFONY__ENV__MAILER_PASSWORD: ${MAILER_PASSWORD}
      SYMFONY__ENV__TWOFACTOR_SENDER: ${TWOFACTOR_SENDER}
      SYMFONY__ENV__FOSUSER_REGISTRATION: "false"
    ports:
      - "127.0.0.1:8003:80"
    volumes:
      - image-data:/var/www/wallabag/web/assets/images
      - app-data:/var/www/wallabag/data
      - site-config-data:/var/www/wallabag/vendor/j0k3r/graby-site-config
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  image-data:
  app-data:
  site-config-data:


networks:
  traefik:
    external: true
