keys:
  - &primary ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKnH3JJcsZnksInIdffC18IkcI2IGxnvyQBv3j+/MHsm
creation_rules:
  - path_regex: xray/[^/]+\.yaml$
    key_groups:
      - age:
          - *primary
  - path_regex: \.env$
    key_groups:
      - age:
          - *primary
  - path_regex: \.ini$
    key_groups:
      - age:
          - *primary
