version: '3'

services:
  traefik:
    image: traefik:v2.6
    restart: always
    command:
      - --log.level=INFO
      - --accesslog=true
      - --api=true
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.network=traefik
      - --providers.file.directory=/etc/traefik/dynamic_config/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs/:/etc/traefik/certs/
      - ./traefik.yaml:/etc/traefik/dynamic_config/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
    networks:
      - traefik

networks:
  traefik:
    external: true
