version: '3'

services:
  snell-server:
    build:
      context: .
      args:
        VERSION: v4.0.1
    restart: always
    network_mode: host
    volumes:
      - ./snell-server.conf:/etc/snell/snell-server.conf
