version: '3'

services:
  snell-server:
    build:
      context: .
      args:
        VERSION: v5.0.0
    restart: always
    network_mode: host
    environment:
      LISTEN: ${LISTEN}
      PSK: ${PSK}
      IPV6: ${IPV6}
