; ENC[AES256_GCM,data:CFTfIasxSaUQ214i3ELjYxarc3fm2fv3PV8JzVODWJz2,iv:pRIr5wkn/1RAECIko5HFEkFOsT0Mtw1HQv88RR1cdMk=,tag:+VggKdeZD6rmFxTPkprfXA==,type:comment]
[app]

; ENC[AES256_GCM,data:xIvqBUL6yeiJux4jW3+oX6T/t7lYNBdVj4GsDM97o//na7t4l9uGVYoQ6etUNXhKwjUYztuTgkhS/MG6fLqCkoCpigI0Ow5ESo0SKB4UGjXQGW82XU7oFnfDwomnnH+Ysyd2t7kqNHvzwCY5F3Uo9nuOTfG+RWvJZjPiC4Ti19lzS7sSY2GRB/HwSZO3dLwj4Ezwzk/dODBXhkaXkWsN2WmqsJeHSuXVy8zu5kqxxFdV8gxlMypsY8YQSQY7GmVx2/bCxg9I2+lMHjbAfqTasaF+ecmY72ZC5qd4wLnAtqUbe4Mt7RSQraBSyWPKdw==,iv:Y+DfmkHLs8Kkp/JPSCNPui9wKSYDFUoC69MmoS6iMdU=,tag:WQPwy13gx10lcB2Ih2GdSA==,type:comment]
[book ""]
name             = ENC[AES256_GCM,data:ST4b9NTpn3eP,iv:dhfSvQT9O3NgoenX66xWu43GLmNsqql/MMO+2bFwoCU=,tag:xggXLpOp24M1vX2r+ArHKA==,type:str]
top_dir          = ENC[AES256_GCM,data:LXf0Dg==,iv:xP0LWcOtnrD3AuYyYqPXb2gMXAafrLnHi8oYLRi9WgA=,tag:crmuu7KsGFx9atZRmzaiyw==,type:str]
data_dir         = 
tree_dir         = ENC[AES256_GCM,data:zW12mXxgTpQP,iv:anm5duwHJBPbbrfa9Ia93b+R2Gcb+WtPC/u74SSHsec=,tag:LXt+3twPnj/WSX9pXp2Uaw==,type:str]
index            = ENC[AES256_GCM,data:SJaYvgJMseDVORtU/ezUditopGo=,iv:9ebDoZr6NoVHYRUwf4rU5YOsz8MmLLStVS37mxUKFyE=,tag:rwGN70wu6rmxCfWaxj4CSA==,type:str]
no_tree          = ENC[AES256_GCM,data:08vYDjM=,iv:V93UJDtlM3CuiMhnKyPlPqGA9sd0sn/1myqtPjQpg3o=,tag:A/NipQ3ZB23gpvdUN7BrDw==,type:str]
new_at_top       = ENC[AES256_GCM,data:jniTons=,iv:dmbB8BTQe+xXPoFmZ/iPGxvO2JPEBV9e9ABAU2p3NVE=,tag:awZUawfucPuFn4GfFWq1GA==,type:str]
inclusive_frames = ENC[AES256_GCM,data:hEuHhw==,iv:JEiYCWu0HPnkYQmOHbR1+lYLJML7uJIidt777LOxgoU=,tag:KTlMzwQQPrz4/wgXVdYKXQ==,type:str]
static_index     = ENC[AES256_GCM,data:nSIJDg==,iv:fWOgIjqkjRhyruiYxy0X2DokILr/6sA672xpGW/cxF8=,tag:aUo2i0/kH0PCQpO/4EDhxQ==,type:str]
rss_root         = 
rss_item_count   = ENC[AES256_GCM,data:oYw=,iv:Sx97FB0Sy3rr5oYw4VrzVDPlx1d6mFBCn7CT/rtdQ4M=,tag:zXBS4fnaiINSiMJMPB5lnQ==,type:str]

[auth "admin"]
user       = ENC[AES256_GCM,data:I6GTNmI=,iv:dpJgGMUNKkHmtE5LNfRbdajnaEqSPCOQqKXOl/M5YIg=,tag:cGMVADcjsTrfjjIp54hTjw==,type:str]
pw         = ENC[AES256_GCM,data:1T/Oeqe3nxFccX/8Xv6rcECSgclEQh9ceTJ3l+5VFYMl/1ptT/neRMTWQIL5Sb2wsXVBpGzWz91qtJFLDZ3ihhwYohAZIBc+YKuCQKG/+66Z4tDqG+LC25D86sPAhd5vjlwAxkq6cJitcZfANGx/6dffJFVdiA==,iv:USkbfgrWfiZ+lwg+gy4/Esejb6q520XLtAfoChVYPWY=,tag:GhJKU/hDJyzUNuyk4kDIYg==,type:str]
permission = ENC[AES256_GCM,data:qCmH,iv:tboC2xlAgy/Hwb3bI+VNT03Jq2H+Pv1wA/CRnWLcgTI=,tag:rrWqj2sM3sGpBO8v9ecRlg==,type:str]

; ENC[AES256_GCM,data:gJbhkQfJg7nDUDGhgeLs26wjLkBctLmyMKaeLFDvTw+v9IOr6ncoqHFIWgp5kP7S/NtSWOeNXp64aA==,iv:76auRL7eQXFuCWurWR2lP+1uiIH0hbNPJvJVTyyVg1k=,tag:910ol8PpoX9cJ435wXCOMQ==,type:comment]
[server]
port = ENC[AES256_GCM,data:ckSZmg==,iv:liBbiaRsSfrGsPX9FYItE09nC7955PGYEXXzhuVk9Pw=,tag:wYY+ZYA1nDGMPoj3gPugAQ==,type:str]
host = ENC[AES256_GCM,data:X9Vpl991Rg==,iv:hwCbXhTNr/4WVkfm6MsfCnzNGn0fBSm2zyoWkCDQXIU=,tag:7Og+LrhVbbOdWH7+c6+rgg==,type:str]

; ENC[AES256_GCM,data:NfcPkGz2k7s3FijmwZ+nnEGGOley3XWxzE0lqRMqC/gO3oMeGwDBwoy3E6rwsbWUR8T0p10ShGjnVD3tRmAZR5vCCnpH+6TeMMQvtBX6x6cyd/TcF02+rcU7pzQrmUu9xBn658k=,iv:xEvUmbmBgkAdj0GDwd7ySCwmzeumrVMGV3sCIyZO6oQ=,tag:JTR8D6wFm2ThlVWVBynG5w==,type:comment]
[browser]

[sops]
age__list_0__map_enc       = """-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFFCNGJlZyByN0JT
eTMzaUNCMWJPRmI1cmpaRWpFS2JDekhWOUNnRGQ4MGI5akhPK3dZCjBiaXYxQkJP
Z0hucmdNNUc0aU5samhsZUtCYWo2aUlwS2U0MWRzK25tTEkKLS0tIG0zSHpEdG1O
UFB3ZFZrajZDZmd3OVBsZWhqcGZDRHFKQVg0ejdVUlRWSXcKrhJffNb6OyU7xqPP
JQeb2l6MvLEwPME/8LV60GApjBjqUSy42ARS0+jRCPVoAVz6DzDskFn6YG/sBz7U
Ogs7+w==
-----END AGE ENCRYPTED FILE-----
"""
age__list_0__map_recipient = ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKnH3JJcsZnksInIdffC18IkcI2IGxnvyQBv3j+/MHsm
lastmodified               = 2026-05-10T14:47:35Z
mac                        = ENC[AES256_GCM,data:7hB2Zi7PyLdOHJSPDCJWfhK3eOXTWvuvAcntkFY/BYsZMub5sbDx+WiTjHQkUyXn2Rynd20+QxtIHDvKaoXx9Ku7OX6Yfu1OMwvlfK9m5sCcOngYBz/VNFem39VppV6KlQ3uShtLIAgzScMYKbnaP89xvt+U6y2gvTWk8hrskyQ=,iv:KICFMkufHRMFfPU6Afw+LTQGFjsw52huMxmlnT+z9/4=,tag:KcecBkQ8fOF8qcLTYEQrKg==,type:str]
unencrypted_suffix         = _unencrypted
version                    = 3.13.0
